config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  post '/guest_sign_in', to: 'homes#guest_sign_in'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resource :users, only: [:show] do
    post 'start', on: :collection
  end
  resource :contents, only: [:show, :create, :destroy]
  resources :accounts, only: [:index, :create, :edit, :update, :destroy] do
    get 'search', on: :collection
    get 'search_sub', on: :collection
  end
  resources :single_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
    get 'scroll', on: :collection
  end
  resources :cash_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
    get 'scroll', on: :collection
  end
  resources :card_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
  end
  resources :trial_balances, only: [:index] do
    get 'select', on: :collection
  end
  resources :transition_tables, only: [:index] do
    get 'select', on: :collection
  end
  resources :ledgers, only: [:index] do
    get 'select', on: :collection
  end
  resource :years, only: [:update] do
    post 'select', on: :collection
  end
  resources :single_entry_imports, only: [:index, :create, :edit, :update, :destroy] do
    get 'import', on: :collection
    delete 'all_destroy', on: :collection
    get 'download', on: :collection
  end
end

app/controllers/cash_entries_controller.rb
class CashEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :select_start_month_to_end_month, only: [:index]
  after_action :discard_flash_if_xhr

  def select
    @accounts = current_user.accounts_index_from_total_account('現預金')
  end

  def index
    @self_code = params[:self_code]
    if @self_code == ''
      flash[:danger] = '表示する月を選択してください。'
      respond_to do |format|
        format.js { render ajax_redirect_to(request.referer) }
      end
    else
      @self_id = current_user.code_id(@self_code)
      if params[:start_month]
        # search mode
        # 日付の入力が正しければ採用し、入力がないor誤りの場合、最初に選択した期間を採用
        @get_start_month = params[:start_month].to_i
        @get_end_month = params[:end_month].to_i
        if Date.valid_date?(current_user.year, params[:month].to_i, params[:day].to_i)
          range = Date.new(current_user.year, params[:month].to_i, params[:day].to_i)
        else
          range = current_user.start_date_to_end_date(@get_start_month, @get_end_month)
        end
        # 入力された内容で検索
        @journals = current_user.journal_index_from_self_code(@self_code, range, 0)
        unless params[:nonself_code] == ''
          nonself_id = current_user.code_id(params[:nonself_code].to_i)
          @journals = @journals.where(debit_id: nonself_id).or(@journals.where(credit_id: nonself_id))
        end
        @journals = @journals.where(debit_id: @self_id, amount: params[:received_amount].to_i) unless params[:received_amount] == ''
        @journals = @journals.where(credit_id: @self_id, amount: params[:invest_amount].to_i) unless params[:invest_amount] == ''
        @journals = @journals.where('description LIKE ?', "%#{params[:description]}%") unless params[:description] == ''

        @journal = Journal.new
      else
        # nomal mode
        if @get_start_month == 0
          flash[:danger] = '表示する月を選択してください。'
          respond_to do |format|
            format.js { render ajax_redirect_to(request.referer) }
          end
        else
          range = current_user.start_date_to_end_date(@get_start_month, @get_end_month)
          @journals = current_user.journal_index_from_self_code(@self_code, range, 0)
          @journal = Journal.new
        end
      end
    end
  end

  def create
    @journal = Journal.new(journal_params)
    if @journal.self_create_and_update_account_balance_in_simple_entry(current_user)
      @journal_new = Journal.new
    else
      flash[:danger] = '入力が正しくない項目があります'
    end
    @self_code = @journal.self_code
    @self_id = current_user.code_id(@self_code)
  end

  def edit
    @self_code = params[:self_code]
    @self_id = current_user.code_id(@self_code)
    @journal = Journal.find(params[:id])
    @journal.arrange_for_display_in_simple_entry(@self_id)
  end

  def update
    @journal = Journal.find(params[:id])
    if @journal.self_update_and_update_account_balance_in_simple_entry(current_user, journal_params)
      @self_code = @journal.self_code
      @self_id = current_user.code_id(@self_code)
    else
      @self_code = @journal.self_code
      @self_id = current_user.code_id(@self_code)
      flash[:danger] = '入力が正しくない項目があります'
      @journal.arrange_for_display_in_simple_entry(@self_id)
    end
  end

  def destroy
    journal = Journal.find(params[:id])
    @id = journal.id
    unless journal.delete_after_updating_balance
      flash[:danger] = '仕訳の削除に失敗しました'
    end
  end

  def search
    @self_code = params[:self_code]
    @start_month = params[:start_month]
    @end_month = params[:end_month]
    @activated = params[:activated]
    @journal = Journal.new
  end

  def scroll
    @self_code = params[:self_code]
    self_id = current_user.code_id(@self_code)
    # 日付の入力が正しければ採用し、入力がないor誤りの場合、最初に選択した期間を採用
    start_month = params[:start_month].to_i
    end_month = params[:end_month].to_i
    if Date.valid_date?(current_user.year, params[:month].to_i, params[:day].to_i)
      range = Date.new(current_user.year, params[:month].to_i, params[:day].to_i)
    else
      range = current_user.start_date_to_end_date(start_month, end_month)
    end
    # データの取得
    offset = params[:offset]
    @journals = current_user.journal_index_from_self_code(@self_code, range, offset)
    # 検索ワードがあれば絞り込み
    unless params[:nonself_code] == ''
      nonself_id = current_user.code_id(params[:nonself_code].to_i)
      @journals = @journals.where(debit_id: nonself_id).or(@journals.where(credit_id: nonself_id))
    end
    @journals = @journals.where(debit_id: self_id, amount: params[:received_amount].to_i) unless params[:received_amount] == ''
    @journals = @journals.where(credit_id: self_id, amount: params[:invest_amount].to_i) unless params[:invest_amount] == ''
    @journals = @journals.where('description LIKE ?', "%#{params[:description]}%") unless params[:description] == ''

    @journals.each do |journal|
      journal.arrange_for_display_in_simple_entry(self_id)
    end
  end

  private

  def journal_params
    params.require(:journal).permit(:month, :day, :self_code, :nonself_code, :received_amount, :invest_amount, :description)
  end
end

app/helpers/cash_entries_helper.rb
module CashEntriesHelper
end

app/views/cash_entries/_edit.html.erb
<%= form_with model: journal, url: cash_entry_path(journal), class:'entry__edit-form-group', remote: true do |f| %>
  <div class='entry__new-td--date'>
    <%= f.text_field :month, autofocus: true, tabindex: 1, class:'entry__form--date' %>
  </div>
  <div class='entry__new-td--date'>
    <%= f.text_field :day, tabindex: 2, class:'entry__form--date' %>
  </div>
  <div class='entry__new-td--nonself-code'>
    <%= f.text_field :nonself_code, tabindex: 3, class:'entry__form--nonself-code' %>
  </div>
  <div class='entry__new-td--name'>
    <%= f.text_field :nonself_name, disabled: true, class:'entry__form--name' %>
  </div>
  <div class='entry__new-td--amount'>
    <%= f.text_field :received_amount, tabindex: 4, class:'entry__form--amount' %>
  </div>
  <div class='entry__new-td--amount'>
    <%= f.text_field :invest_amount, tabindex: 5, class:'entry__form--amount' %>
  </div>
  <div class='entry__new-td--description'>
    <%= f.text_field :description, tabindex: 6, class:'entry__form--description' %>
  </div>
  <div class='entry__index-td--btn'>
    <%= f.hidden_field :self_code, class:'entry__form--self-code' %>
    <%= f.button type: 'submit', tabindex: 7, class:'entry__edit-btn' do %>
      <i class="fas fa-save"></i>
    <% end %>
  </div>
<% end %>

app/views/cash_entries/_explanation.html.erb
<a href='' class='modal__open-btn'><i class="far fa-question-circle"></i></a>
<div class='modal__area'>
  <div class='modal__background'></div>
  <a href='' class='modal__close-btn'><i class="far fa-times-circle"></i></a>
  <div class='modal__content'>
    <ul>
      <li>
        <h4 class='modal__content-title'>表示する月と科目を選んでください</h4>
        <p>表示したい期間をドラッグ&ドロップで選択してください。ドラッグした月の色が黄色に変わります。️</p>
        <p>また「科目選択」から入力を行う勘定科目を選択してください。</p>
        <p>期間と勘定科目を選択したら「表示」ボタンを押してください。仕訳一覧や入力フォームが表示されます。</p>
        <%= image_tag 'cash-entry/select-month.png', height: '60px', width: 'auto' %>
      </li>
      <li>
        <h4 class='modal__content-title'>入力フォーム</h4>
        <p>仕訳を入力することができます。</p>
        <p>摘要の入力欄以外はEnterを押すと次の項目に移動し、摘要の入力欄でEnterを押すと仕訳を保存します。</p>
        <p>摘要の入力欄以外は全角で入力した数字が自動で半角に変換されます。</p>
        <p>科目コード入力欄ではコードを入力すると科目候補一覧を表示し、存在する科目を入力し終えると右側に科目名を表示します。</p>
        <p>仕訳を保存すると仕訳一覧に追加され、入力フォームの先頭にフォーカスが移ります。</p>
        <%= image_tag 'cash-entry/new.png', height: '240px', width: 'auto' %>
      </li>
      <li>
        <h4 class='modal__content-title'>仕訳一覧</h4>
        <p>指定した期間中の仕訳一覧が表示されます。</p>
        <p>表示する仕訳が15件以上ある場合は最初に15件表示され、一覧部分トップまでスクロールすると追加の仕訳を取得し表示します。</p>
        <p>各仕訳右側の1つ目のアイコンをクリックすると編集モードに変わり、2つ目のアイコンをクリックすると仕訳を削除します。</p>
        <%= image_tag 'cash-entry/index.png', height: '120px', width: 'auto' %>
        <p>【編集モード】</p>
        <p>登録済みの仕訳の内容を編集することができます。編集後は右側のアイコンをクリックし保存してください。</p>
        <%= image_tag 'cash-entry/edit.png', height: '48px', width: 'auto' %>
      </li>
      <li>
        <h4 class='modal__content-title'>「検索モードにする」ボタン</h4>
        <p>ボタンをクリックすると検索モードになり、ボタンと入力フォームが黄色に変わります。</p>
        <p>もう一度ボタンをクリックすると検索モードを終了します。</p>
        <%= image_tag 'single-entry/search-mode-btn.png', height: '50px', width: 'auto' %>
        <p>入力フォームの任意の項目を入力し、摘要の入力欄でEnterを押すと仕訳一覧の内容を更新します。</p>
        <p>※月で絞り込みを行う場合は、「表示する月を選んでください」にて絞り込みを行なってください。</p>
        <%= image_tag 'cash-entry/search-mode-form.png', height: '47px', width: 'auto' %>
      </li>
    </ul>
  </div>
</div>

app/views/cash_entries/_new.html.erb
<%= form_with model: journal, url: cash_entries_path, class:'entry__form-group', remote: true do |f| %>
  <div class='entry__index-tr--sinple-entry'>
    <div class='entry__new-td--date'>
      <%= f.text_field :month, autofocus: true, tabindex: 11, class:'entry__form--date' %>
    </div>
    <div class='entry__new-td--date'>
      <%= f.text_field :day, tabindex: 12, class:'entry__form--date' %>
    </div>
    <div class='entry__new-td--nonself-code'>
      <%= f.text_field :nonself_code, tabindex: 13, class:'entry__form--nonself-code' %>
    </div>
    <div class='entry__new-td--name'>
      <%= f.text_field :nonself_name, disabled: true, class:'entry__form--name' %>
    </div>
    <div class='entry__new-td--amount'>
      <%= f.text_field :received_amount, tabindex: 14, class:'entry__form--amount' %>
    </div>
    <div class='entry__new-td--amount'>
      <%= f.text_field :invest_amount, tabindex: 15, class:'entry__form--amount' %>
    </div>
    <div class='entry__new-td--description'>
      <%= f.text_field :description, tabindex: 16, class:'entry__form--description' %>
    </div>
    <div class='entry__new-td--btn'>
      <%= f.hidden_field :self_code, class:'entry__form--self-code' %>
      <%= f.submit '', tabindex: 17 %>
    </div>
  </div>
<% end %>

<!-- 科目候補表示 -->
<div class='entry__subbox'></div>

app/views/cash_entries/_search.html.erb
<%= form_with url: cash_entries_path, method: :get, class:'entry__form-group', remote: true do |f| %>
  <div class='entry__index-tr--sinple-entry'>
    <div class='entry__new-td--date'>
      <%= f.text_field :month, autofocus: true, tabindex: 11, class:'entry__form--date' %>
    </div>
    <div class='entry__new-td--date'>
      <%= f.text_field :day, tabindex: 12, class:'entry__form--date' %>
    </div>
    <div class='entry__new-td--nonself-code'>
      <%= f.text_field :nonself_code, tabindex: 13, class:'entry__form--nonself-code' %>
    </div>
    <div class='entry__new-td--name'>
      <%= f.text_field :nonself_name, disabled: true, class:'entry__form--name' %>
    </div>
    <div class='entry__new-td--amount'>
      <%= f.text_field :received_amount, tabindex: 14, class:'entry__form--amount' %>
    </div>
    <div class='entry__new-td--amount'>
      <%= f.text_field :invest_amount, tabindex: 15, class:'entry__form--amount' %>
    </div>
    <div class='entry__new-td--description'>
      <%= f.text_field :description, tabindex: 16, class:'entry__form--description' %>
    </div>
    <div class='entry__new-td--btn'>
      <%= f.hidden_field :start_month, class:'entry__form--start-month' %>
      <%= f.hidden_field :end_month, class:'entry__form--end-month' %>
      <%= f.hidden_field :self_code, class:'entry__form--self-code' %>
      <%= f.submit '', tabindex: 17 %>
    </div>
  </div>
<% end %>

<!-- 科目候補表示 -->
<div class='entry__subbox'></div>

app/views/cash_entries/_show.html.erb
<div class='entry__index-tr<%= journal.id %>'>
  <div class='entry__index-td--date'><%= journal.date.month %></div>
    <div class='entry__index-td--date'><%= journal.date.day %></div>
    <% if journal.debit_id == self_id %>
      <div class='entry__index-td--nonself-code'><%= journal.credit.code %></div>
      <div class='entry__index-td--name'><%= journal.credit.name %></div>
      <div class='entry__index-td--amount'><%= journal.amount.to_s(:delimited) %></div>
      <div class='entry__index-td--amount'>0</div>
    <% else %>
      <div class='entry__index-td--nonself-code'><%= journal.debit.code %></div>
      <div class='entry__index-td--name'><%= journal.debit.name %></div>
      <div class='entry__index-td--amount'>0</div>
      <div class='entry__index-td--amount'><%= journal.amount.to_s(:delimited) %></div>
    <% end %>
  <div class='entry__index-td--description'><%= journal.description %></div>
  <div class='entry__index-td--btn'>
    <%= link_to edit_cash_entry_path(id: journal.id, self_code: self_code), class:'entry__index-link', remote: true do %>
      <i class="fas fa-edit"></i>
    <% end %>
  </div>
  <div class='entry__index-td--btn'>
    <%= link_to cash_entry_path(journal), method: :delete, class:'entry__index-link', remote: true do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </div>
</div>

app/views/cash_entries/create.js.erb
<% if flash[:danger] %>
  $('.flash').html('<%= j(render 'layouts/flash') %>');
  $('.cash-entry__new').html('<%= j(render 'new', journal: @journal) %>');
  <!-- self-codeをセット -->
  $('.entry__form--self-code').val(<%= @self_code %>);
  <!-- create後、autofocusが効かなくなるのでjqueryで対応 -->
  $('#journal_month').focus();
<% else %>
  $('.flash').html('<%= j(render 'layouts/flash') %>');
  $('.entry__index-tbody').append('<%= j(render 'show', journal: @journal, self_id: @self_id, self_code: @self_code) %>');
  $('.cash-entry__new').html('<%= j(render 'new', journal: @journal_new) %>');
  <!-- self-codeをセット -->
  $('.entry__form--self-code').val(<%= @self_code %>);
  <!-- create後、autofocusが効かなくなるのでjqueryで対応 -->
  $('#journal_month').focus();
  <!-- table最下部までスクロール -->
  $('.entry__index-tbody').animate({scrollTop: $('.entry__index-tbody')[0].scrollHeight}, 'fast');
<% end %>

app/views/cash_entries/destroy.js.erb
$('.entry__index-tr<%= @id %>').html('');

app/views/cash_entries/edit.js.erb
$('.entry__index-tr<%= @journal.id %>').html('<%= j(render 'cash_entries/edit', journal: @journal) %>');

app/views/cash_entries/index.js.erb
<!-- 一度初期化してから再度仕訳を表示 -->
$('.flash').html('<%= j(render 'layouts/flash') %>');
$('.entry__index-tbody').html('');
<% @journals.each do |journal| %>
  $('.entry__index-tbody').prepend('<%= j(render 'show', journal: journal, self_id: @self_id, self_code: @self_code) %>');
<% end %>

$('.cash-entry__new').html('<%= j(render 'new', journal: @journal) %>');
$('.cash-entry__search-mode').html('<%= j(render 'layouts/search-mode-simple',path: search_cash_entries_path) %>');
<!-- self-codeをセット -->
$('.entry__form--self-code').val(<%= @self_code %>);
$('.search-mode__form-self-code').val(<%= @self_code %>);
<!-- search-modeに開始月と終了月をセット -->
$('.search-mode__form-start').val('<%= @get_start_month %>');
$('.search-mode__form-end').val('<%= @get_end_month %>');
<!-- table最下部までスクロール -->
$('.entry__index-tbody').animate({scrollTop: $('.entry__index-tbody')[0].scrollHeight}, 'fast');

app/views/cash_entries/search.js.erb
<% if @activated == 'true' %>
  $('.cash-entry__new').html('<%= j(render 'new', journal: @journal) %>');
  $('.search-mode__form-activated').val(false);
  $('.search-mode__form-btn').css('background', 'rgba(255, 255, 255, 1)');
<% else %>
  $('.cash-entry__new').html('<%= j(render 'search') %>');
  $('.entry__form--start-month').val('<%= @start_month %>');
  $('.entry__form--end-month').val('<%= @end_month %>');
  $('.entry__form--self-code').val('<%= @self_code %>');
  $('.search-mode__form-activated').val(true);
  $('.entry__index-tr--sinple-entry').css('background', 'rgba(255, 192, 0, 1)');
  $('.search-mode__form-btn').css('background', 'rgba(255, 192, 0, 1)');
<% end %>

app/views/cash_entries/select.html.erb
<!-- 画面説明 -->
<%= render 'explanation' %>

<div class='cash-entry'>
  <!-- 入力月選択フォーム -->
  <div class='cash-entry__select-month'>
    <%= render 'layouts/select-month-account', path: cash_entries_path %>
  </div>

  <!-- 検索モードボタン -->
  <div class='cash-entry__search-mode'>
    <!-- #indexにて非同期生成 -->
  </div>

  <!-- 仕訳表示 -->
  <div class='cash-entry__index'>
    <div class='entry__index-table'>
      <div class='entry__index-thead'>
        <div class='entry__index-tr--sinple-entry'>
          <div class='entry__index-th--date'>月</div>
          <div class='entry__index-th--date'>日</div>
          <div class='entry__index-th--nonself-code'>相手科目コード</div>
          <div class='entry__index-th--name'>相手科目名</div>
          <div class='entry__index-th--amount'>入金額</div>
          <div class='entry__index-th--amount'>出金額</div>
          <div class='entry__index-th--description'>摘要</div>
        </div>
      </div>
      <div class='entry__index-tbody'>
        <!-- #indexにて非同期生成 -->
      </div>
    </div>
  </div>

  <!-- 仕訳入力 -->
  <div class='cash-entry__new'>
    <!-- #indexにて非同期生成 -->
  </div>
</div>

app/views/cash_entries/update.js.erb
<% if flash[:danger] %>
  $('.flash').html('<%= j(render 'layouts/flash') %>');
  $('.entry__index-tr<%= @journal.id %>').html('<%= j(render 'cash_entries/edit',  journal: @journal, self_id: @self_id, self_code: @self_code) %>');
<% else %>
  $('.flash').html('<%= j(render 'layouts/flash') %>');
  $('.entry__index-tr<%= @journal.id %>').html('<%= j(render 'cash_entries/show',  journal: @journal, self_id: @self_id, self_code: @self_code) %>');
<% end %>