config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  post '/guest_sign_in', to: 'homes#guest_sign_in'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resource :users, only: [:show] do
    post 'start', on: :collection
  end
  resource :contents, only: [:show, :create, :destroy]
  resources :accounts, only: [:index, :create, :edit, :update, :destroy] do
    get 'search', on: :collection
    get 'search_sub', on: :collection
  end
  resources :single_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
    get 'scroll', on: :collection
  end
  resources :cash_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
    get 'scroll', on: :collection
  end
  resources :card_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
  end
  resources :trial_balances, only: [:index] do
    get 'select', on: :collection
  end
  resources :transition_tables, only: [:index] do
    get 'select', on: :collection
  end
  resources :ledgers, only: [:index] do
    get 'select', on: :collection
  end
  resource :years, only: [:update] do
    post 'select', on: :collection
  end
  resources :single_entry_imports, only: [:index, :create, :edit, :update, :destroy] do
    get 'import', on: :collection
    delete 'all_destroy', on: :collection
    get 'download', on: :collection
  end
end

app/controllers/single_entry_imports_controller.rb
class SingleEntryImportsController < ApplicationController
  before_action :authenticate_user!

  def index
    @imports = Import.where(user_id: current_user.id, pending: false)
  end

  def create
    # csvファイルが読み込まれた場合のみ処理を行う
    if params[:file] && File.extname(params[:file].original_filename) == '.csv'
      result_hash = Import.create_import_from_csv(current_user, params[:file])
      flash[:success] = "#{result_hash[:success_count]}件の仕訳を取り込みました。"
      flash[:danger] = "#{result_hash[:error_rows]}、#{result_hash[:error_count]}件のエラーが発生しました。" if result_hash[:error_count] > 0
    else
      flash[:danger] = 'ファイルを読み込むことができませんでした。'
    end
    redirect_to single_entry_imports_path
  end

  def edit
    @import = Import.find(params[:id])
    @import.arrange_for_display
  end

  def update
    @import = Import.find(params[:id])
    unless @import.self_update(current_user, import_params)
      flash[:danger] = '入力が正しくない項目があります'
      @import.arrange_for_display
    end
  end

  def destroy
    import = Import.find(params[:id])
    @id = import.id
    unless import.destroy
      falsh[:danger] = '仕訳の削除に失敗しました'
    end
  end

  def import
    imports = Import.where(user_id: current_user.id, pending: false)
    # 取得した仕訳を待機中に変更
    imports.update_all(pending: true)
    CsvImportJob.perform_later(current_user.id)
    flash[:success] = '仕訳の取込を実行しています。しばらくしてから画面を再表示してください。'
    redirect_to single_entry_imports_path
  end

  def all_destroy
    Import.all_destroy(current_user)
    flash[:success] = '取込待ち仕訳一覧の仕訳を全て削除しました。'
    redirect_to single_entry_imports_path
  end

  def download
    download_file_name = 'app/assets/csv/取込用csvファイル.csv'
    send_file download_file_name
  end

  private

  def import_params
    params.require(:import).permit(:month, :day, :debit_code, :credit_code, :amount, :description)
  end
end

app/helpers/single_entry_imports_helper.rb
module SingleEntryImportsHelper
end

app/views/single_entry_imports/_edit.html.erb
<%= form_with model: import, url: single_entry_import_path(import), class:'entry__edit-form-group', remote: true do |f| %>
  <div class='entry__new-td--date'>
    <%= f.text_field :month, autofocus: true, tabindex: 1, class:'entry__form--date' %>
  </div>
  <div class='entry__new-td--date'>
    <%= f.text_field :day, tabindex: 2, class:'entry__form--date' %>
  </div>
  <div class='entry__new-td--code'>
    <%= f.text_field :debit_code, tabindex: 3, class:'entry__form--code' %>
  </div>
  <div class='entry__new-td--name'>
    <%= f.text_field :debit_name, disabled: true, class:'entry__form--name' %>
  </div>
  <div class='entry__new-td--code'>
    <%= f.text_field :credit_code, tabindex: 4, class:'entry__form--code' %>
  </div>
  <div class='entry__new-td--name'>
    <%= f.text_field :credit_name, disabled: true, class:'entry__form--name' %>
  </div>
  <div class='entry__new-td--amount'>
    <%= f.text_field :amount, tabindex: 5, class:'entry__form--amount' %>
  </div>
  <div class='entry__new-td--description'>
    <%= f.text_field :description, tabindex: 6, class:'entry__form--description' %>
  </div>
  <div class='entry__index-td--btn'>
    <%= f.button type: 'submit', tabindex: 7, class:'entry__edit-btn' do %>
      <i class="fas fa-save"></i>
    <% end %>
  </div>
<% end %>

app/views/single_entry_imports/_show.html.erb
<div class='entry__index-tr<%= import.id %>'>
  <div class='entry__index-td--date'><%= import.date.month %></div>
  <div class='entry__index-td--date'><%= import.date.day %></div>
  <div class='entry__index-td--code'><%= import.debit.code %></div>
  <div class='entry__index-td--name'><%= import.debit.name %></div>
  <div class='entry__index-td--code'><%= import.credit.code %></div>
  <div class='entry__index-td--name'><%= import.credit.name %></div>
  <div class='entry__index-td--amount'><%= import.amount.to_s(:delimited) %></div>
  <div class='entry__index-td--description'><%= import.description %></div>
  <div class='entry__index-td--btn'>
    <%= link_to edit_single_entry_import_path(import), class:'entry__index-link', remote: true do %>
      <i class="fas fa-edit"></i>
    <% end %>
  </div>
  <div class='entry__index-td--btn'>
    <%= link_to single_entry_import_path(import), method: :delete, class:'entry__index-link', remote: true do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </div>
</div>

app/views/single_entry_imports/destroy.js.erb
$('.entry__index-tr<%= @id %>').html('');

app/views/single_entry_imports/edit.js.erb
$('.entry__index-tr<%= @import.id %>').html('<%= j(render 'single_entry_imports/edit', import: @import) %>');

app/views/single_entry_imports/index.html.erb
<!-- 画面説明 -->
<a href='' class='modal__open-btn'><i class="far fa-question-circle"></i></a>
<div class='modal__area'>
  <div class='modal__background'></div>
  <a href='' class='modal__close-btn'><i class="far fa-times-circle"></i></a>
  <div class='modal__content'>
    <ul>
      <li>
        <h4 class='modal__content-title'>CSV新規取込</h4>
        <p>取込を行うCSVファイルを選択し「インポート」ボタンを押してください。</p>
        <p>取込可能なCSVファイルは「CSVダウンロード」ボタンよりダウンロードして編集してください。</p>
        <%= image_tag 'single-entry-import/download.png', height: '30px', width: 'auto' %>
        <p>正常にインポートしたファイルは取込待ち仕訳一覧に追加されます。※この時点では残高に反映していません。</p>
        <p>不正なデータがある場合、画面上部にエラーメッセージが表示され取込は行われません。</p>
      </li>
      <li>
        <h4 class='modal__content-title'>取込待ち仕訳一覧</h4>
        <p>正常にインポートした仕訳が表示されます。</p>
        <p>一覧に表示されている状態では仮登録となっており、入力画面と同様に右側のアイコンから編集や削除することが可能です。</p>
        <%= image_tag 'single-entry-import/index.png', height: '120px', width: 'auto' %>
      </li>
      <li>
        <h4 class='modal__content-title'>「取込実行」ボタン</h4>
        <p>取込待ち仕訳一覧のデータを本登録します。実行後、入力画面やレポート画面に反映されます。</p>
        <%= image_tag 'single-entry-import/create.png', height: '30px', width: 'auto' %>
      </li>
      <li>
        <h4 class='modal__content-title'>「全て削除」ボタン</h4>
        <p>取込待ち仕訳一覧のデータを全て削除します。</p>
        <p>インポートが一部うまくいかず、再度インポートを行いたい場合などにご利用ください。</p>
        <%= image_tag 'single-entry-import/all-destroy.png', height: '30px', width: 'auto' %>
      </li>
    </ul>
  </div>
</div>

<div class='single-entry-import'>
  <!-- csv新規取込フォーム -->
  <h4 class='single-entry-import__new-title'>CSV新規取込</h4>
  <%= form_with url: single_entry_imports_path, method: :post, class:'single-entry-import__form-group', local:true do |f| %>
    <%= f.file_field :file, class:'single-entry-import__file-field' %>
    <%= f.submit 'インポート', class:'single-entry-import__form-btn' %>
  <% end %>

  <!-- 仕訳表示 -->
  <h4 class='single-entry-import__index-title'>取込待ち仕訳一覧</h4>
  <%= button_to 'CSVダウンロード', download_single_entry_imports_path, method: :get, class:'single-entry-import__btn' %>
  <%= link_to '取込実行', import_single_entry_imports_path, class:'single-entry-import__btn' %>
  <%= link_to '全て削除', all_destroy_single_entry_imports_path, method: :delete, class:'single-entry-import__btn' %>
  <div class='single-entry-import__index'>
    <div class='entry__index-table'>
      <div class='entry__index-thead'>
        <div class='entry__index-tr'>
          <div class='entry__index-th--date'>月</div>
          <div class='entry__index-th--date'>日</div>
          <div class='entry__index-th--code'>借方コード</div>
          <div class='entry__index-th--name'>借方科目名</div>
          <div class='entry__index-th--code'>貸方コード</div>
          <div class='entry__index-th--name'>貸方科目名</div>
          <div class='entry__index-th--amount'>金額</div>
          <div class='entry__index-th--description'>摘要</div>
        </div>
      </div>
      <div class='entry__index-tbody--import'>
        <% @imports.each do |import| %>
          <%= render 'show', import: import %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- 科目候補表示 -->
  <div class='entry__subbox'></div>
</div>

app/views/single_entry_imports/update.js.erb
<% if flash[:danger] %>
  $('.flash').html('<%= j(render 'layouts/flash') %>');
  $('.entry__index-tr<%= @import.id %>').html('<%= j(render 'single_entry_imports/edit', import: @import) %>');
<% else %>
  $('.flash').html('<%= j(render 'layouts/flash') %>');
  $('.entry__index-tr<%= @import.id %>').html('<%= j(render 'single_entry_imports/show', import: @import) %>');
<% end %>