config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  post '/guest_sign_in', to: 'homes#guest_sign_in'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resource :users, only: [:show] do
    post 'start', on: :collection
  end
  resource :contents, only: [:show, :create, :destroy]
  resources :accounts, only: [:index, :create, :edit, :update, :destroy] do
    get 'search', on: :collection
    get 'search_sub', on: :collection
  end
  resources :single_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
    get 'scroll', on: :collection
  end
  resources :cash_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
    get 'scroll', on: :collection
  end
  resources :card_entries, only: [:index, :create, :edit, :update, :destroy] do
    get 'select', on: :collection
    get 'search', on: :collection
  end
  resources :trial_balances, only: [:index] do
    get 'select', on: :collection
  end
  resources :transition_tables, only: [:index] do
    get 'select', on: :collection
  end
  resources :ledgers, only: [:index] do
    get 'select', on: :collection
  end
  resource :years, only: [:update] do
    post 'select', on: :collection
  end
  resources :single_entry_imports, only: [:index, :create, :edit, :update, :destroy] do
    get 'import', on: :collection
    delete 'all_destroy', on: :collection
    get 'download', on: :collection
  end
end

app/views/layouts/_errors.html.erb
<!-- validation errors -->
<% if obj.errors.any? %>
  <h5 class='errors__title'><%= obj.errors.count %>件のエラーが発生しました。</h5>
  <ul class='errors__list'>
    <% obj.errors.full_messages.each do|message| %>
      <li class='errors__list-item'><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class='flash__<%= message_type %>'>
    <div class='flash__message'>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/layouts/_search-mode-simple.html.erb
<div class='search-mode'>
  <%= form_with url: path, method: :get, class:'search-mode__form-group', remote: true do |f| %>
    <%= f.hidden_field :start_month, class:'search-mode__form-start' %>
    <%= f.hidden_field :end_month, class:'search-mode__form-end' %>
    <%= f.hidden_field :activated, :value => false, class:'search-mode__form-activated' %>
    <%= f.hidden_field :self_code, class:'search-mode__form-self-code' %>
    <%= f.submit '検索モードにする', class:'search-mode__form-btn' %>
  <% end %>
</div>

app/views/layouts/_search-mode.html.erb
<div class='search-mode'>
  <%= form_with url: path, method: :get, class:'search-mode__form-group', remote: true do |f| %>
    <%= f.hidden_field :start_month, class:'search-mode__form-start' %>
    <%= f.hidden_field :end_month, class:'search-mode__form-end' %>
    <%= f.hidden_field :activated, :value => false, class:'search-mode__form-activated' %>
    <%= f.hidden_field :self_code, class:'search-mode__form-self-code' %>
    <%= f.submit '検索モードにする', class:'search-mode__form-btn' %>
  <% end %>
</div>

app/views/layouts/_select-month-account.html.erb
<div class='select-month'>
  <p class='select-month__title'>表示する月と科目を選んでください</p>
  <%= form_with url:  path, method: :get, class:'select-month__form-group', remote: true do |f| %>
    <div class='select-month__boxes'>
      <% 12.times do |n| %>
        <div class='select-month__box'>
          <!-- 試算表→総勘定元帳の場合true -->
          <% if @get_start_month != nil %>
            <% if @get_start_month == n + 1 %>
              <%= f.check_box "mon#{n + 1}", checked: true, class:'select-month__checkbox' %>
              <%= f.label "mon#{n + 1}", "#{n + 1}月", class:'select-month__label--second', id:"month#{n + 1}" %>

            <% elsif @get_end_month == n + 1 %>
              <%= f.check_box "mon#{n + 1}", checked: true,  class:'select-month__checkbox' %>
              <%= f.label "mon#{n + 1}", "#{n + 1}月", class:'select-month__label--second', id:"month#{n + 1}" %>
            <% elsif @get_start_month < n + 1 && n + 1 < @get_end_month %>
              <%= f.check_box "mon#{n + 1}", class:'select-month__checkbox' %>
              <%= f.label "mon#{n + 1}", "#{n + 1}月", class:'select-month__label--second', id:"month#{n + 1}" %>
            <% else %>
              <%= f.check_box "mon#{n + 1}", class:'select-month__checkbox' %>
              <%= f.label "mon#{n + 1}", "#{n + 1}月", class:'select-month__label', id:"month#{n + 1}" %>
            <% end %>
          <% else %>
            <%= f.check_box "mon#{n + 1}", class:'select-month__checkbox' %>
            <%= f.label "mon#{n + 1}", "#{n + 1}月", class:'select-month__label', id:"month#{n + 1}" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div clas='select-month__form-boxes'>
      <div class='select-month__account'>
        <%= f.select :self_code, @accounts, { include_blank: '科目選択', selected: @self_code}, {class:'select-month__account-form'} %>
      </div>
      <div class='select-month__box-btn'>
        <%= f.submit '表示', class:'select-month__btn' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_select-month-from1.html.erb
<div class='select-month-from1'>
  <p class='select-month-from1__title'>表示する月を選んでください</p>
  <%= form_with url:  path, method: :get, class:'select-month-from1__form-group', remote: true do |f| %>
    <div class='select-month-from1__boxes'>
      <!-- 1月はチェックボックスではなくhidden_fieldにする -->
      <div class='select-month-from1__box'>
        <%= f.hidden_field :mon1, :value => 1, class:'select-month-from1__hidden' %>
        <%= f.label 'mon1', '1月', class:'select-month-from1__label--first-only', id:'month1' %>
      </div>
      <% 11.times do |n| %>
        <div class='select-month-from1__box'>
          <%= f.check_box "mon#{n + 2}", class:'select-month-from1__checkbox' %>
          <%= f.label "mon#{n + 2}", "#{n + 2}月", class:'select-month-from1__label', id:"month#{n + 2}" %>
        </div>
      <% end %>
    </div>
    <div class='select-month-from1__box-btn'>
      <%= f.submit '表示', class:'select-month-from1__btn' %>
    </div>
  <% end %>
</div>

app/views/layouts/_select-month.html.erb
<div class='select-month'>
  <p class='select-month__title'>表示する月を選んでください</p>
  <%= form_with url:  path, method: :get, class:'select-month__form-group', remote: true do |f| %>
    <div class='select-month__boxes'>
      <% 12.times do |n| %>
        <div class='select-month__box'>
          <%= f.check_box "mon#{n + 1}", class:'select-month__checkbox' %>
          <%= f.label "mon#{n + 1}", "#{n + 1}月", class:'select-month__label', id:"month#{n + 1}" %>
        </div>
      <% end %>
    </div>
    <div class='select-month__box-btn'>
      <%= f.submit '表示', class:'select-month__btn' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceLearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <script src="https://kit.fontawesome.com/efe3d01fd5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ローディング -->
    <div class="loader">Loading...</div>
    
    <header>
      <ul class='navbar'>
        <li class='navbar__logo'>
          <%= link_to root_path, class:'navbar__logo-link' do %>
            <%= image_tag 'logo.png', class:'navbar__logo-image' %>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class='navbar__item'>
            <p class='navbar__user-name'><%= current_user.name %></p>
            <p>
              <% if current_user.year == 0 %>
                <p class='navbar__user-year'>データ未作成</p>
              <% else %>
               <p class='navbar__user-year'><%= current_user.year %>年度</p>
              <% end %>
            </p>
          </li>
          <li class='navbar__item'>
            <%= link_to '学習コンテンツ', contents_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
          </li>
          <li class='navbar__item'>
            <%= link_to 'マイページ', users_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
          </li>
          <li class='navbar__dropdown'>
            <a class='navbar__item-link'>入力</a>
            <ul class='navbar__dropdown-list'>
              <li class='navbar__dropdown-item'>
                <i class="fas fa-caret-right"></i>
                <%= link_to '単一入力', select_single_entries_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
              </li>
              <li class='navbar__dropdown-item'>
                <i class="fas fa-caret-right"></i>
                <%= link_to '現金入力', select_cash_entries_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
              </li>
              <li class='navbar__dropdown-item'>
                <i class="fas fa-caret-right"></i>
                <%= link_to 'カード入力', select_card_entries_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
              </li>
              <li class='navbar__dropdown-item'>
                <i class="fas fa-caret-right"></i>
                <%= link_to 'CSV取込', single_entry_imports_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
              </li>
            </ul>
          </li>
          <li class='navbar__dropdown'>
            <a class='navbar__item-link'>レポート</a>
            <ul class='navbar__dropdown-list'>
              <li class='navbar__dropdown-item'>
                <i class="fas fa-caret-right"></i>
                <%= link_to '試算表', select_trial_balances_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
              </li>
              <li class='navbar__dropdown-item'>
                <i class="fas fa-caret-right"></i>
                <%= link_to '推移表', select_transition_tables_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
              </li>
              <li class='navbar__dropdown-item'>
                <i class="fas fa-caret-right"></i>
                <%= link_to '総勘定元帳', select_ledgers_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
              </li>
            </ul>
          </li>
          <li class='navbar__item'>
            <%= link_to '設定', accounts_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
          </li>
        <% else %>
          <li class='navbar__item'>
            <%= link_to '学習コンテンツ', contents_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
          </li>
          <li class='navbar__item'>
            <%= link_to '新規登録', new_user_registration_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
          </li>
          <li class='navbar__item'>
            <%= link_to 'ログイン', new_user_session_path, data: { 'turbolinks' => false }, class:'navbar__item-link' %>
          </li>
          <li class='navbar__item'>
            <%= link_to 'ゲストログイン', guest_sign_in_path, method: :post, class:'navbar__item-link' %>
          </li>
        <% end %>
      </ul>
    </header>
    <main>
      <!-- flash message -->
      <div class='flash'>
        <%= render 'layouts/flash' %>
      </div>

      <%= yield %>
    </main>
    <footer>
      <p class='footer__text'>Copyright ︎©︎2021 Finance Learning</p>
    </footer>
  </body>
</html>